apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wilApplication
  namespace: dev
spec:
  project: default
  source:
    repoURL: https://github.com/aaitbelh/aerrazik.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
