apiVersion: v1
kind: Pod
metadata:
  name: wil
  namespace: dev
spec:
  containers:
  - name: wil-v2
    image: wil42/playground:v2
    ports: 
    - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: wil
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: wil
  ports:
  - protocol: TCP
    port: 8888
